//-----------------------------------------
// Core Volume & Activity Measures
//-----------------------------------------

Total Patients =
DISTINCTCOUNT ( Patient[PatientID] )

Total Patients Admitted =
COUNTROWS ( Admissions )

Total Inpatients =
CALCULATE (
    [Total Patients],
    KEEPFILTERS ( Admissions[PatientType] = "Inpatient" )
)

Total Outpatients =
CALCULATE (
    [Total Patients],
    KEEPFILTERS ( Admissions[PatientType] = "Outpatient" )
)

// Used in the "Inpatients vs Outpatients Trend" visual
Inpatients vs Outpatients Label =
SELECTEDVALUE ( Admissions[PatientType] )

//-----------------------------------------
// Cost & Wait Time Measures
//-----------------------------------------

Total Treatment Cost =
SUM ( TreatmentCosts[TotalCost] )

Avg Treatment Cost =
DIVIDE ( [Total Treatment Cost], [Total Patients Admitted] )

Total ER Wait Minutes =
SUM ( WaitingTimes[ERWaitMinutes] )

Avg ER Wait Time (mins) =
AVERAGE ( WaitingTimes[ERWaitMinutes] )

// Avg wait time by department is the same measure
// with Department on the visual axis.
Avg Wait Time by Department =
[Avg ER Wait Time (mins)]

//-----------------------------------------
// Staff Measures
//-----------------------------------------

Total Staff =
COUNTROWS ( Staff )

Available Staff =
CALCULATE (
    [Total Staff],
    KEEPFILTERS ( Staff[IsAvailable] = TRUE ()
    )
)

//-----------------------------------------
// Patient Satisfaction Measures
//-----------------------------------------

Total Survey Responses =
COUNTROWS ( SatisfactionSurvey )

Overall Satisfaction Score (1–5) =
AVERAGE ( SatisfactionSurvey[OverallSatisfactionScore] )

Satisfaction % Neutral =
DIVIDE (
    CALCULATE (
        COUNTROWS ( SatisfactionSurvey ),
        KEEPFILTERS ( SatisfactionSurvey[OverallSatisfactionLabel] = "Neutral" )
    ),
    [Total Survey Responses]
)

Satisfaction % Excellent =
DIVIDE (
    CALCULATE (
        COUNTROWS ( SatisfactionSurvey ),
        KEEPFILTERS ( SatisfactionSurvey[OverallSatisfactionLabel] = "Excellent" )
    ),
    [Total Survey Responses]
)

Satisfaction % Good =
DIVIDE (
    CALCULATE (
        COUNTROWS ( SatisfactionSurvey ),
        KEEPFILTERS ( SatisfactionSurvey[OverallSatisfactionLabel] = "Good" )
    ),
    [Total Survey Responses]
)

// Doctor explained treatment understandably (Likert 1–5)
Explain Treatment Score =
AVERAGE ( SatisfactionSurvey[ExplainTreatmentScore] )

// I had confidence and trust in the treating physician (Likert 1–5)
Trust Physician Score =
AVERAGE ( SatisfactionSurvey[TrustPhysicianScore] )

//-----------------------------------------
// Length of Stay & Readmissions
//-----------------------------------------

Average Days Of Stay =
AVERAGE ( BedOccupancy[LengthOfStayDays] )

Patients Count (LOS Distribution) =
COUNTROWS ( BedOccupancy )

Readmissions Within 30 Days =
COUNTROWS (
    FILTER (
        Readmissions,
        Readmissions[Within30DaysFlag] = TRUE ()
    )
)

Readmissions Within 30 Days (QoQ) =
[Readmissions Within 30 Days]    // plotted by Quarter from the Date field

//-----------------------------------------
// Utility Measures
//-----------------------------------------

Selected Year =
SELECTEDVALUE ( Admissions[Year] )

Selected Department =
SELECTEDVALUE ( Admissions[Department] )
